org: grupo4utecv3
app: kambiop2p
service: kambiop2p-mercado

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole
  environment:
    OFFERS_TABLE: ${self:service}-offers-${self:provider.stage}
    EXTERNAL_RATES_TABLE: ${self:service}-external-rates-${self:provider.stage}

functions:
  getOffers:
    handler: handler.get_offers
    events:
      - http:
          path: offers
          method: get
          cors: true

  createOffer:
    handler: handler.create_offer
    events:
      - http:
          path: offers/create
          method: post
          cors: true

  deleteOffer:
    handler: handler.delete_offer
    events:
      - http:
          path: offers/{id}
          method: delete
          cors: true

  getMarketRates:
    handler: handler.get_market_rates
    events:
      - http:
          path: market/rates
          method: get
          cors: true

resources:
  Resources:
    OffersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.OFFERS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StatusIndex
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    ExternalRatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.EXTERNAL_RATES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: bank_name
            AttributeType: S
        KeySchema:
          - AttributeName: bank_name
            KeyType: HASH


custom:
  pythonRequirements:
    dockerizePip: false
    layer: false
