org: grupo4utecv3
app: kambiop2p
service: kambiop2p-usuarios

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole
  environment:
    USERS_TABLE: ${self:service}-users-${self:provider.stage}
    PROFILES_TABLE: ${self:service}-profiles-${self:provider.stage}
    REPUTATION_TABLE: ${self:service}-reputation-${self:provider.stage}

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  getProfile:
    handler: handler.get_profile
    events:
      - http:
          path: user/profile/{id}
          method: get
          cors: true

  updateReputation:
    handler: handler.update_reputation
    events:
      - http:
          path: user/reputation
          method: patch
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    ProfilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PROFILES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH

    ReputationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REPUTATION_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    layer: false
