service: kambiop2p-frontend

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: kambiop2p-frontend-${self:provider.stage}
      localDir: out
      acl: public-read

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: kambiop2p-frontend-${self:provider.stage}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebsiteBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Sub '${WebsiteBucket.Arn}/*'

  Outputs:
    WebsiteURL:
      Value: !GetAtt WebsiteBucket.WebsiteURL
      Description: URL del sitio web
